// test module
require('./render.test.js')
require('./bnnAlign.test.js')
require('./bnnSize.test.js')
require('./bnnPosition.test.js')
require('./bnnGradient.test.js')
require('./bnnImport.test.js')
require('./bnnVariable.test.js')
require('./getParam.test.js')
require('./cliInput.test.js')
require('./cliVersion.test.js')
require('./cliInputOutput.test.js')
